### ISSUE TITLE
One Checkpoint Model Missing

### ISSUE THREAD

**Issue by cwaubert** [jokofa/NeuroLS#1]
Hey there,

 I believe that the **checkpoint model [NeuroLS/checkpoints/jssp_30x15_uniform/SELECT_EPSILON-SELECT_LS+-ALL  /ep74_model_rew=0.009175.ckpt](https://github.com/jokofa/NeuroLS/blob/master/checkpoints/jssp_30x15_uniform/SELECT_EPSILON-SELECT_LS%2B-ALL/ep74_model_rew%3D0.009175.ckpt)** is **empty**. 

Is that so and if so, would you mind uploading it?

**Comment by jokofa** [comment]
Hi there, 

Thank you for raising the issue.
I checked my local files but I fear that I do not have the original versions of the checkpoints there since I do not have access to my old work computer. Let me check, if there still exist some old backups which include this checkpoint.

**Comment by jokofa** [comment]
Hi again,

so I was able to recover and re-upload the missing checkpoint. Sorry for the inconvenience. 
If there is anything else missing or not working, feel free to just reopen the issue.
